#define CANNY_THRESHOLD_LOW 120
#define CANNY_THRESHOLD_HIGHT 240
#define ROI_START_Y_RATIO 0.66
#define ROI_HEIGHT_RATIO 0.21
#define IPM_START_RATIO 0.44
#define TOP_DIFF_RATIO 0.5
#define BOTTOM_DIFF_RATIO 0.20
#define MAX_FRAME_MOMENTUM 5